### ISSUE TITLE
AIIDALAB_HOME hardcoded in docker-compose.yml

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-docker-stack-demo#23]
Hi folks, 

I am currently trying to use this repo as a template/starting point for my deployment of my own Aiidalab application.
I noticed a small issue, though it might also be a misunderstanding on my part.

It looks to me that `--home-dir` parameter to `control.py` currently is not passed to docker-compose, and the path to the home directory is harcoded to `~/aiidalab` in `docker-compose.yml`.

https://github.com/aiidalab/aiidalab-docker-stack-demo/blob/099c9b4a95838db38256a292c2c6b1b327f48387/docker-compose.yml#L14

**Comment by danielhollas** [comment]
@csadorf thanks, that's good to know. My goal is not only to be able to launch AiidaLab, but to also install my AiiDAlab app and its dependecies, including setting up the codes/computers in the AiiDA DB. Not sure if `aiidalab-launch` is a good tool for that, but I will check it out for sure.

**Comment by csadorf** [comment]
The scope of aiidalab-launch is to enable users to hassle-free launch (and manage) AiiDAlab on their own systems. You can configure default apps and also specify a custom image. So it might meet your use case. Feel free to keep me in the loop, I can try to help with the implementation.

I will leave this issue open until either `control.py` is fixed or we replaced the advertised workflow to use aiidalab-launch instead.

**Comment by csadorf** [comment]
Closing this, since [AiiDAlab Launch](https://aiidalab.readthedocs.io/en/latest/usage/index.html#aiidalab-launch) as primary way to deploy AiiDAlab should address this issue.
